export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const UPDATE_PURCHASSBLE = 'UPDATE_PURCHASSBLE'

export const RESET_INGREDIENT = 'RESET_INGREDIENT'

export const LOAD_ORDER = 'LOAD_ORDER'
export const ORDER_LOAD_FAILED = 'ORDER_LOAD_FAILED'